/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ChannelRole } from "../types";

export const s: Record<string, any> = {
  overlay:     { position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000 },
  modal:       { width: "560px", maxWidth: "95vw", maxHeight: "85vh", background: "var(--col-bg-elevated)", border: "1px solid var(--col-border)", borderRadius: "16px", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 16px 48px rgba(0,0,0,0.6)" },
  header:      { padding: "20px 24px", borderBottom: "1px solid var(--col-border)", display: "flex", alignItems: "center", justifyContent: "space-between", flexShrink: 0 },
  title:       { fontSize: "16px", fontWeight: 700, color: "var(--col-text-primary)" },
  closeBtn:    { width: "30px", height: "30px", background: "transparent", border: "none", color: "var(--col-text-muted)", cursor: "pointer", padding: 0, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: "6px" },
  tabs:        { display: "flex", borderBottom: "1px solid var(--col-border)", flexShrink: 0, overflowX: "auto" },
  tab: (active: boolean) => ({ padding: "12px 20px", fontSize: "13px", fontWeight: active ? 700 : 400, color: active ? "var(--col-text-primary)" : "var(--col-text-muted)", border: "none", borderBottom: active ? "2px solid var(--col-accent)" : "2px solid transparent", background: "transparent", cursor: "pointer", fontFamily: "inherit", whiteSpace: "nowrap" }),
  body:        { flex: 1, overflowY: "auto", padding: "20px 24px" },
  field:       { marginBottom: "16px" },
  label:       { display: "block", fontSize: "11px", fontWeight: 700, color: "var(--col-text-secondary)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "6px" },
  input:       { width: "100%", boxSizing: "border-box", background: "var(--col-bg-input)", border: "1px solid var(--col-border)", borderRadius: "8px", padding: "10px 14px", color: "var(--col-text-primary)", fontSize: "14px", outline: "none", fontFamily: "inherit" },
  textarea:    { width: "100%", boxSizing: "border-box", minHeight: "80px", background: "var(--col-bg-input)", border: "1px solid var(--col-border)", borderRadius: "8px", padding: "10px 14px", color: "var(--col-text-primary)", fontSize: "14px", outline: "none", fontFamily: "inherit", resize: "vertical" },
  saveBtn:     { padding: "10px 20px", background: "var(--col-accent)", border: "none", borderRadius: "8px", color: "#fff", fontSize: "13px", fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  dangerBtn:   { padding: "8px 16px", background: "transparent", border: "1px solid var(--col-danger)", borderRadius: "8px", color: "var(--col-danger)", fontSize: "13px", cursor: "pointer", fontFamily: "inherit" },
  secondaryBtn: { padding: "8px 14px", background: "var(--col-bg-hover)", border: "none", borderRadius: "8px", color: "var(--col-text-primary)", fontSize: "13px", cursor: "pointer", fontFamily: "inherit" },
  memberRow:   { display: "flex", alignItems: "center", gap: "10px", padding: "10px 0", borderBottom: "1px solid var(--col-bg-elevated)" },
  memberAvatar: { fontSize: "22px", flexShrink: 0 },
  memberName:  { flex: 1, fontSize: "14px", color: "var(--col-text-primary)", overflow: "hidden", textOverflow: "ellipsis" },
  roleBadge: (role?: ChannelRole | string) => ({
    padding: "2px 8px", borderRadius: "10px", fontSize: "11px", fontWeight: 600,
    background: role === "owner" ? "rgba(88,101,242,0.13)" : role === "manager" ? "rgba(240,165,0,0.13)" : role === "viewer" ? "rgba(242,63,66,0.13)" : "var(--col-bg-hover)",
    color: role === "owner" ? "var(--col-link)" : role === "manager" ? "var(--col-warning-gold)" : role === "viewer" ? "var(--col-danger)" : "var(--col-text-secondary)",
  }),
  permRow:     { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 0", borderBottom: "1px solid var(--col-bg-elevated)" },
  permLabel:   { fontSize: "14px", color: "var(--col-text-primary)" },
  permDesc:    { fontSize: "12px", color: "var(--col-text-muted)", marginTop: "2px" },
  toggle: (on: boolean) => ({ width: "40px", height: "22px", borderRadius: "11px", background: on ? "var(--col-accent)" : "var(--col-bg-subtle)", position: "relative", cursor: "pointer", border: "none", transition: "background 0.2s", flexShrink: 0 }),
  toggleKnob: (on: boolean) => ({ position: "absolute", top: "3px", left: on ? "21px" : "3px", width: "16px", height: "16px", borderRadius: "50%", background: "#fff", transition: "left 0.2s" }),
  inviteRow:   { background: "var(--col-bg-input)", border: "1px solid var(--col-border)", borderRadius: "8px", padding: "12px 14px", marginBottom: "10px" },
  inviteCode:  { fontFamily: "monospace", fontSize: "14px", color: "var(--col-text-primary)", marginBottom: "4px" },
  inviteMeta:  { fontSize: "11px", color: "var(--col-text-muted)" },
  inviteActions: { display: "flex", gap: "8px", marginTop: "8px" },
  error:       { background: "rgba(242,63,66,0.08)", border: "1px solid var(--col-danger)", borderRadius: "8px", padding: "8px 12px", color: "var(--col-danger)", fontSize: "12px", marginBottom: "10px" },
  success:     { background: "rgba(35,165,90,0.08)", border: "1px solid var(--col-success)", borderRadius: "8px", padding: "8px 12px", color: "var(--col-success)", fontSize: "12px", marginBottom: "10px" },
  toggleRow:   { display: "flex", alignItems: "center", gap: "12px", padding: "12px 0" },
  sectionTitle: { fontSize: "12px", fontWeight: 700, color: "var(--col-accent)", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "12px", marginTop: "4px" },
};
