/* eslint-disable @typescript-eslint/no-explicit-any */
import type { ChannelRole } from "../types";

export const s: Record<string, any> = {
  overlay:     { position: "fixed", inset: 0, background: "rgba(0,0,0,0.7)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 1000 },
  modal:       { width: "560px", maxWidth: "95vw", maxHeight: "85vh", background: "#1e1e2e", border: "1px solid #2d2d3f", borderRadius: "16px", display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 16px 48px rgba(0,0,0,0.6)" },
  header:      { padding: "20px 24px", borderBottom: "1px solid #2d2d3f", display: "flex", alignItems: "center", justifyContent: "space-between", flexShrink: 0 },
  title:       { fontSize: "16px", fontWeight: 700, color: "#f2f3f5" },
  closeBtn:    { width: "30px", height: "30px", background: "transparent", border: "none", color: "#5c6068", cursor: "pointer", padding: 0, display: "flex", alignItems: "center", justifyContent: "center", borderRadius: "6px" },
  tabs:        { display: "flex", borderBottom: "1px solid #2d2d3f", flexShrink: 0, overflowX: "auto" },
  tab: (active: boolean) => ({ padding: "12px 20px", fontSize: "13px", fontWeight: active ? 700 : 400, color: active ? "#f2f3f5" : "#5c6068", border: "none", borderBottom: active ? "2px solid #5865f2" : "2px solid transparent", background: "transparent", cursor: "pointer", fontFamily: "inherit", whiteSpace: "nowrap" }),
  body:        { flex: 1, overflowY: "auto", padding: "20px 24px" },
  field:       { marginBottom: "16px" },
  label:       { display: "block", fontSize: "11px", fontWeight: 700, color: "#949ba4", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "6px" },
  input:       { width: "100%", boxSizing: "border-box", background: "#0f0f1a", border: "1px solid #2d2d3f", borderRadius: "8px", padding: "10px 14px", color: "#f2f3f5", fontSize: "14px", outline: "none", fontFamily: "inherit" },
  textarea:    { width: "100%", boxSizing: "border-box", minHeight: "80px", background: "#0f0f1a", border: "1px solid #2d2d3f", borderRadius: "8px", padding: "10px 14px", color: "#f2f3f5", fontSize: "14px", outline: "none", fontFamily: "inherit", resize: "vertical" },
  saveBtn:     { padding: "10px 20px", background: "#5865f2", border: "none", borderRadius: "8px", color: "#fff", fontSize: "13px", fontWeight: 700, cursor: "pointer", fontFamily: "inherit" },
  dangerBtn:   { padding: "8px 16px", background: "transparent", border: "1px solid #f23f42", borderRadius: "8px", color: "#f23f42", fontSize: "13px", cursor: "pointer", fontFamily: "inherit" },
  secondaryBtn: { padding: "8px 14px", background: "#2d2d3f", border: "none", borderRadius: "8px", color: "#f2f3f5", fontSize: "13px", cursor: "pointer", fontFamily: "inherit" },
  memberRow:   { display: "flex", alignItems: "center", gap: "10px", padding: "10px 0", borderBottom: "1px solid #1e1e2e" },
  memberAvatar: { fontSize: "22px", flexShrink: 0 },
  memberName:  { flex: 1, fontSize: "14px", color: "#f2f3f5", overflow: "hidden", textOverflow: "ellipsis" },
  roleBadge: (role?: ChannelRole | string) => ({
    padding: "2px 8px", borderRadius: "10px", fontSize: "11px", fontWeight: 600,
    background: role === "owner" ? "#5865f220" : role === "manager" ? "#f0a50020" : role === "viewer" ? "#f23f4220" : "#2d2d3f",
    color: role === "owner" ? "#7289da" : role === "manager" ? "#f0a500" : role === "viewer" ? "#f23f42" : "#949ba4",
  }),
  permRow:     { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 0", borderBottom: "1px solid #1e1e2e" },
  permLabel:   { fontSize: "14px", color: "#f2f3f5" },
  permDesc:    { fontSize: "12px", color: "#5c6068", marginTop: "2px" },
  toggle: (on: boolean) => ({ width: "40px", height: "22px", borderRadius: "11px", background: on ? "#5865f2" : "#3a3a4f", position: "relative", cursor: "pointer", border: "none", transition: "background 0.2s", flexShrink: 0 }),
  toggleKnob: (on: boolean) => ({ position: "absolute", top: "3px", left: on ? "21px" : "3px", width: "16px", height: "16px", borderRadius: "50%", background: "#fff", transition: "left 0.2s" }),
  inviteRow:   { background: "#0f0f1a", border: "1px solid #2d2d3f", borderRadius: "8px", padding: "12px 14px", marginBottom: "10px" },
  inviteCode:  { fontFamily: "monospace", fontSize: "14px", color: "#f2f3f5", marginBottom: "4px" },
  inviteMeta:  { fontSize: "11px", color: "#5c6068" },
  inviteActions: { display: "flex", gap: "8px", marginTop: "8px" },
  error:       { background: "#f23f4215", border: "1px solid #f23f42", borderRadius: "8px", padding: "8px 12px", color: "#f23f42", fontSize: "12px", marginBottom: "10px" },
  success:     { background: "#23a55a15", border: "1px solid #23a55a", borderRadius: "8px", padding: "8px 12px", color: "#23a55a", fontSize: "12px", marginBottom: "10px" },
  toggleRow:   { display: "flex", alignItems: "center", gap: "12px", padding: "12px 0" },
  sectionTitle: { fontSize: "12px", fontWeight: 700, color: "#5865f2", textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: "12px", marginTop: "4px" },
};
