// Shared inline-style map for ChatArea and its sub-components.
// Typed as a plain object so TypeScript accepts CSSProperties values.
/* eslint-disable @typescript-eslint/no-explicit-any */
export const s: Record<string, any> = {
  area:       { flex: 1, overflowY: "auto", padding: "16px 24px", display: "flex", flexDirection: "column", gap: "2px" },
  empty:      { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", color: "#5c6068", gap: "12px" },
  emptyIcon:  { fontSize: "48px" },
  loadMore: {
    alignSelf: "center", padding: "8px 20px", background: "#2d2d3f",
    border: "1px solid #3a3a4f", borderRadius: "20px", color: "#949ba4",
    fontSize: "13px", cursor: "pointer", marginBottom: "16px",
  },
  dateDivider: {
    display: "flex", alignItems: "center", gap: "12px", margin: "12px 0",
    color: "#5c6068", fontSize: "11px", fontWeight: 600,
    textTransform: "uppercase", letterSpacing: "0.5px",
  },
  dividerLine: { flex: 1, height: "1px", background: "#2d2d3f" },
  msgGroup:   { display: "flex", flexDirection: "column", gap: "1px", marginBottom: "4px" },
  msgRow: {
    display: "flex", alignItems: "flex-start", gap: "12px",
    padding: "3px 8px", borderRadius: "8px", position: "relative",
  },
  avatarCol:   { width: "36px", flexShrink: 0, display: "flex", alignItems: "flex-start", justifyContent: "center", paddingTop: "2px" },
  avatarEmoji: { fontSize: "22px", lineHeight: "1" },
  msgContent:  { flex: 1, minWidth: 0 },
  msgHeader:   { display: "flex", alignItems: "baseline", gap: "8px", marginBottom: "2px", flexWrap: "wrap" },
  username:    (isOwn: boolean) => ({ fontWeight: 600, fontSize: "14px", color: isOwn ? "#7289da" : "#f2f3f5" }),
  adminBadge:  { fontSize: "12px", color: "#faa61a" },
  pinnedBadge: { fontSize: "10px", color: "#5c6068", background: "#2d2d3f", padding: "1px 6px", borderRadius: "4px", display: "inline-flex", alignItems: "center", gap: "3px" },
  timestamp:   { fontSize: "11px", color: "#5c6068" },
  editedTag:   { fontSize: "10px", color: "#5c6068", fontStyle: "italic" },
  replyQuote: {
    background: "#2d2d3f", borderLeft: "3px solid #5865f2", borderRadius: "4px",
    padding: "4px 10px", marginBottom: "6px", fontSize: "12px", color: "#949ba4",
    display: "flex", alignItems: "center", gap: "6px",
    overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap",
  },
  replyAuthor: { color: "#7289da", fontWeight: 600, flexShrink: 0 },
  replyText:   { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  msgImage: {
    maxWidth: "360px", maxHeight: "300px", borderRadius: "8px",
    display: "block", marginTop: "4px", cursor: "pointer", border: "1px solid #2d2d3f",
  },
  msgFile: {
    display: "inline-flex", alignItems: "center", gap: "10px",
    background: "#2d2d3f", border: "1px solid #3a3a4f",
    borderRadius: "8px", padding: "10px 14px", marginTop: "4px",
    fontSize: "13px", color: "#949ba4", cursor: "pointer", transition: "background 0.15s",
  },
  fileInfo:    { display: "flex", flexDirection: "column", gap: "2px" },
  fileName:    { color: "#f2f3f5", fontWeight: 500, fontSize: "13px" },
  fileSize:    { color: "#5c6068", fontSize: "11px" },
  reactionsRow: { display: "flex", flexWrap: "wrap", gap: "4px", marginTop: "4px" },
  reactionPill: (isMine: boolean) => ({
    display: "inline-flex", alignItems: "center", gap: "4px", padding: "2px 8px",
    background: isMine ? "#5865f225" : "#2d2d3f",
    border: `1px solid ${isMine ? "#5865f260" : "#3a3a4f"}`,
    borderRadius: "12px", fontSize: "13px", cursor: "pointer",
    color: isMine ? "#7289da" : "#949ba4",
  }),
  actionBar: {
    position: "absolute", top: "-20px", right: "8px",
    display: "flex", gap: "2px", background: "#2d2d3f",
    border: "1px solid #3a3a4f", borderRadius: "8px",
    padding: "3px 4px", zIndex: 10, boxShadow: "0 4px 12px rgba(0,0,0,0.4)",
  },
  actionBtn: {
    background: "transparent", border: "none", color: "#949ba4",
    fontSize: "14px", cursor: "pointer", padding: "3px 6px",
    borderRadius: "4px", lineHeight: "1",
  },
  editTextarea: {
    width: "100%", background: "#0f0f1a", border: "1px solid #5865f2",
    borderRadius: "6px", color: "#f2f3f5", fontSize: "14px",
    lineHeight: "1.5", padding: "8px 10px", resize: "none",
    fontFamily: "inherit", outline: "none", boxSizing: "border-box",
  },
  editActions: { display: "flex", gap: "8px", marginTop: "6px", fontSize: "12px" },
  editSave:    { padding: "4px 12px", background: "#5865f2", border: "none", borderRadius: "4px", color: "#fff", fontSize: "12px", cursor: "pointer", fontFamily: "inherit" },
  editCancel:  { padding: "4px 8px", background: "transparent", border: "none", color: "#949ba4", fontSize: "12px", cursor: "pointer", fontFamily: "inherit" },
  emojiPicker: {
    position: "absolute", top: "-54px", right: "8px",
    display: "flex", gap: "4px", background: "#2d2d3f",
    border: "1px solid #3a3a4f", borderRadius: "10px",
    padding: "6px 8px", zIndex: 20, boxShadow: "0 4px 16px rgba(0,0,0,0.5)",
  },
  emojiBtn: (active: boolean) => ({
    background: active ? "#5865f230" : "transparent",
    border: active ? "1px solid #5865f260" : "1px solid transparent",
    borderRadius: "6px", fontSize: "18px", cursor: "pointer", padding: "3px 4px", lineHeight: "1",
  }),
  modalOverlay: {
    position: "fixed", inset: 0, background: "rgba(0,0,0,0.85)",
    zIndex: 1000, display: "flex", alignItems: "center", justifyContent: "center",
  },
  modalBox: {
    background: "#1e1e2e", border: "1px solid #2d2d3f", borderRadius: "16px",
    padding: "24px", maxWidth: "90vw", maxHeight: "90vh",
    display: "flex", flexDirection: "column", gap: "16px",
    boxShadow: "0 24px 64px rgba(0,0,0,0.6)",
  },
  modalHeader:   { display: "flex", alignItems: "center", justifyContent: "space-between", gap: "16px" },
  modalTitle:    { fontWeight: 600, fontSize: "14px", color: "#f2f3f5", wordBreak: "break-all" },
  modalClose:    { background: "transparent", border: "none", color: "#5c6068", fontSize: "20px", cursor: "pointer", padding: "2px 6px", flexShrink: 0 },
  modalImg:      { maxWidth: "75vw", maxHeight: "70vh", borderRadius: "8px", objectFit: "contain", display: "block" },
  modalFileIcon: { fontSize: "64px", textAlign: "center" },
  modalFileMeta: { color: "#5c6068", fontSize: "13px", textAlign: "center" },
  modalActions:  { display: "flex", gap: "10px", justifyContent: "center" },
  downloadBtn: {
    padding: "8px 20px", background: "#5865f2", border: "none",
    borderRadius: "8px", color: "#fff", fontSize: "13px",
    cursor: "pointer", fontFamily: "inherit", fontWeight: 600,
    textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "6px",
  },
};