/* eslint-disable @typescript-eslint/no-explicit-any */
export const s: Record<string, any> = {
  container:    { padding: "0 16px 16px", flexShrink: 0, position: "relative" },
  replyBar:     { display: "flex", alignItems: "center", gap: "8px", background: "#2d2d3f", borderRadius: "8px 8px 0 0", padding: "6px 12px", borderBottom: "1px solid #3a3a4f", fontSize: "12px", color: "#949ba4" },
  replyIcon:    { color: "#7289da", flexShrink: 0, display: "inline-flex" },
  replyText:    { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  replyClose:   { background: "transparent", border: "none", color: "#5c6068", cursor: "pointer", padding: "0 4px", display: "flex", alignItems: "center", justifyContent: "center" },
  filePreview:  { display: "flex", alignItems: "center", gap: "10px", background: "#2d2d3f", padding: "8px 12px", borderBottom: "1px solid #3a3a4f", fontSize: "12px", color: "#949ba4" },
  fileImg:      { width: "40px", height: "40px", objectFit: "cover", borderRadius: "4px" },
  fileIcon:     { fontSize: "28px" },
  fileRemove:   { background: "transparent", border: "none", color: "#f23f42", cursor: "pointer", marginLeft: "auto", display: "flex", alignItems: "center", justifyContent: "center" },
  wrapper:      { background: "#2d2d3f", border: "1px solid #3a3a4f", borderRadius: "12px", display: "flex", alignItems: "flex-end", gap: "4px", padding: "8px 12px" },
  wrapperWithTop: { borderRadius: "0 0 12px 12px" },
  iconBtn:      { width: "32px", height: "32px", background: "transparent", border: "none", color: "#5c6068", cursor: "pointer", padding: 0, borderRadius: "6px", flexShrink: 0, lineHeight: "1", transition: "color 0.15s, background 0.15s", display: "flex", alignItems: "center", justifyContent: "center" },
  textarea:     { flex: 1, background: "transparent", border: "none", color: "#f2f3f5", fontSize: "14px", lineHeight: "1.5", resize: "none", maxHeight: "160px", minHeight: "20px", outline: "none", fontFamily: "inherit", overflowY: "auto" },
  sendBtn: (active: boolean) => ({
    width: "34px", height: "34px", borderRadius: "8px",
    background: active ? "#5865f2" : "#3a3a4f",
    color: active ? "#fff" : "#5c6068",
    fontSize: "16px", display: "flex", alignItems: "center", justifyContent: "center",
    flexShrink: 0, cursor: active ? "pointer" : "default",
    border: "none", fontFamily: "inherit", transition: "all 0.15s",
  }),
  hint: { fontSize: "11px", color: "#5c6068", marginTop: "4px", paddingLeft: "4px" },
  emojiPanel: {
    position: "absolute", bottom: "calc(100% + 4px)", left: "0",
    background: "#1e1e2e", border: "1px solid #2d2d3f", borderRadius: "12px",
    width: "320px", maxHeight: "280px", overflow: "hidden",
    display: "flex", flexDirection: "column",
    boxShadow: "0 8px 24px rgba(0,0,0,0.4)", zIndex: 100,
  },
  emojiTabs: { display: "flex", borderBottom: "1px solid #2d2d3f", overflow: "hidden" },
  emojiTab: (active: boolean) => ({
    flex: 1, padding: "8px 4px", textAlign: "center",
    fontSize: "11px", color: active ? "#f2f3f5" : "#5c6068",
    background: active ? "#2d2d3f" : "transparent",
    border: "none", cursor: "pointer", fontFamily: "inherit",
    borderBottom: active ? "2px solid #5865f2" : "2px solid transparent",
  }),
  emojiGrid:    { display: "flex", flexWrap: "wrap", gap: "2px", padding: "8px", overflowY: "auto", flex: 1 },
  emojiItem:    { background: "transparent", border: "none", fontSize: "20px", cursor: "pointer", padding: "4px", borderRadius: "6px", lineHeight: "1" },
  mentionDropdown: {
    position: "absolute", bottom: "calc(100% + 4px)", left: "16px",
    background: "#1e1e2e", border: "1px solid #2d2d3f", borderRadius: "8px",
    minWidth: "200px", maxHeight: "200px", overflowY: "auto",
    boxShadow: "0 8px 24px rgba(0,0,0,0.4)", zIndex: 100,
  },
  mentionItem: (active: boolean) => ({
    display: "flex", alignItems: "center", gap: "8px",
    padding: "8px 12px", cursor: "pointer",
    background: active ? "#2d2d3f" : "transparent", fontSize: "13px",
  }),
};
