/* eslint-disable @typescript-eslint/no-explicit-any */
export const s: Record<string, any> = {
  sidebar:      { width: "240px", flexShrink: 0, background: "#1e1e2e", display: "flex", flexDirection: "column", borderRight: "1px solid #2d2d3f", overflow: "hidden" },
  header:       { padding: "16px", borderBottom: "1px solid #2d2d3f", display: "flex", alignItems: "center", justifyContent: "space-between" },
  workspaceName: { fontWeight: 700, fontSize: "15px", color: "#f2f3f5" },
  statusDot: (connected: boolean) => ({ width: "8px", height: "8px", borderRadius: "50%", background: connected ? "#23a55a" : "#f23f42", flexShrink: 0 }),
  scrollArea:   { flex: 1, overflowY: "auto", padding: "8px 0" },
  section:      { marginBottom: "8px" },
  sectionHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "6px 16px", cursor: "pointer" },
  sectionTitle: { fontSize: "11px", fontWeight: 700, color: "#949ba4", textTransform: "uppercase", letterSpacing: "0.5px" },
  addBtn:       { width: "16px", height: "16px", color: "#949ba4", fontSize: "16px", lineHeight: "16px", display: "flex", alignItems: "center", justifyContent: "center", borderRadius: "4px", transition: "all 0.15s" },
  channelItem: (active: boolean) => ({
    display: "flex", alignItems: "center", gap: "6px", padding: "5px 16px", cursor: "pointer",
    background: active ? "#5865f220" : "transparent",
    borderLeft: active ? "2px solid #5865f2" : "2px solid transparent",
    color: active ? "#f2f3f5" : "#949ba4", fontSize: "14px", transition: "all 0.1s",
  }),
  channelName:  { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  dmItem: (active: boolean) => ({
    display: "flex", alignItems: "center", gap: "8px", padding: "5px 16px", cursor: "pointer",
    background: active ? "#5865f220" : "transparent",
    borderLeft: active ? "2px solid #5865f2" : "2px solid transparent",
    transition: "all 0.1s",
  }),
  unreadBadge:  { minWidth: "18px", height: "18px", borderRadius: "9px", background: "#f23f42", color: "#fff", fontSize: "10px", fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", padding: "0 5px", flexShrink: 0 },
  userItem:     { display: "flex", alignItems: "center", gap: "8px", padding: "5px 16px", fontSize: "13px", color: "#949ba4" },
  avatarWrap:   { position: "relative", flexShrink: 0 },
  avatar:       { fontSize: "20px", display: "flex", alignItems: "center", justifyContent: "center" },
  onlineDot: (color: string) => ({ position: "absolute", bottom: -2, right: -2, width: "8px", height: "8px", borderRadius: "50%", background: color, border: "2px solid #1e1e2e" }),
  footer:       { padding: "12px 16px", borderTop: "1px solid #2d2d3f", display: "flex", alignItems: "center", gap: "10px" },
  footerUser:   { flex: 1, overflow: "hidden" },
  footerUsername: { fontSize: "13px", fontWeight: 600, color: "#f2f3f5", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  footerEmail:  { fontSize: "11px", color: "#5c6068", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  logoutBtn:    { padding: "6px", borderRadius: "6px", color: "#f23f42", fontSize: "18px", transition: "background 0.15s" },
  newChannelForm: { padding: "8px 16px", display: "flex", flexDirection: "column", gap: "6px" },
  newChannelInput: { background: "#0f0f1a", border: "1px solid #2d2d3f", borderRadius: "6px", padding: "6px 10px", color: "#f2f3f5", fontSize: "13px", outline: "none" },
  newChannelRow: { display: "flex", gap: "6px" },
  newChannelSubmit: { padding: "6px 12px", background: "#5865f2", borderRadius: "6px", color: "#fff", fontSize: "13px", fontWeight: 600, border: "none", cursor: "pointer" },
  privateToggle: { display: "flex", alignItems: "center", gap: "6px", fontSize: "12px", color: "#949ba4", cursor: "pointer" },
};