/* eslint-disable @typescript-eslint/no-explicit-any */
export const s: Record<string, any> = {
  sidebar:      { width: "240px", flexShrink: 0, background: "var(--col-bg-elevated)", display: "flex", flexDirection: "column", borderRight: "1px solid var(--col-border)", overflow: "hidden" },
  header:       { padding: "16px", borderBottom: "1px solid var(--col-border)", display: "flex", alignItems: "center", justifyContent: "space-between" },
  workspaceName: { fontWeight: 700, fontSize: "15px", color: "var(--col-text-primary)" },
  statusDot: (connected: boolean) => ({ width: "8px", height: "8px", borderRadius: "50%", background: connected ? "var(--col-success)" : "var(--col-danger)", flexShrink: 0 }),
  scrollArea:   { flex: 1, overflowY: "auto", padding: "8px 0" },
  section:      { marginBottom: "8px" },
  sectionHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "6px 16px", cursor: "pointer" },
  sectionTitle: { fontSize: "11px", fontWeight: 700, color: "var(--col-text-secondary)", textTransform: "uppercase", letterSpacing: "0.5px" },
  addBtn:       { width: "16px", height: "16px", color: "var(--col-text-secondary)", fontSize: "16px", lineHeight: "16px", display: "flex", alignItems: "center", justifyContent: "center", borderRadius: "4px", transition: "all 0.15s" },
  iconButton:   { width: "28px", height: "28px", display: "flex", alignItems: "center", justifyContent: "center", background: "transparent", border: "none", color: "var(--col-text-muted)", cursor: "pointer", padding: 0, borderRadius: "6px" },
  channelItem: (active: boolean) => ({
    display: "flex", alignItems: "center", gap: "6px", padding: "5px 16px", cursor: "pointer",
    background: active ? "rgba(88,101,242,0.13)" : "transparent",
    borderLeft: active ? "2px solid var(--col-accent)" : "2px solid transparent",
    color: active ? "var(--col-text-primary)" : "var(--col-text-secondary)", fontSize: "14px", transition: "all 0.1s",
  }),
  channelName:  { flex: 1, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  dmItem: (active: boolean) => ({
    display: "flex", alignItems: "center", gap: "8px", padding: "5px 16px", cursor: "pointer",
    background: active ? "rgba(88,101,242,0.13)" : "transparent",
    borderLeft: active ? "2px solid var(--col-accent)" : "2px solid transparent",
    transition: "all 0.1s",
  }),
  unreadBadge:  { minWidth: "18px", height: "18px", borderRadius: "9px", background: "var(--col-danger)", color: "#fff", fontSize: "10px", fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", padding: "0 5px", flexShrink: 0 },
  userItem:     { display: "flex", alignItems: "center", gap: "8px", padding: "5px 16px", fontSize: "13px", color: "var(--col-text-secondary)" },
  avatarWrap:   { position: "relative", flexShrink: 0 },
  avatar:       { fontSize: "20px", display: "flex", alignItems: "center", justifyContent: "center" },
  onlineDot: (color: string) => ({ position: "absolute", bottom: -2, right: -2, width: "8px", height: "8px", borderRadius: "50%", background: color, border: "2px solid var(--col-bg-elevated)" }),
  footer:       { padding: "12px 16px", borderTop: "1px solid var(--col-border)", display: "flex", alignItems: "center", gap: "10px" },
  footerUser:   { flex: 1, overflow: "hidden" },
  footerUsername: { fontSize: "13px", fontWeight: 600, color: "var(--col-text-primary)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  footerEmail:  { fontSize: "11px", color: "var(--col-text-muted)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  logoutBtn:    { width: "30px", height: "30px", padding: 0, borderRadius: "6px", color: "var(--col-danger)", background: "transparent", border: "none", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "background 0.15s" },
  themeBtn:     { width: "30px", height: "30px", padding: 0, borderRadius: "6px", color: "var(--col-text-secondary)", background: "transparent", border: "none", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "background 0.15s", fontSize: "16px", flexShrink: 0 },
  newChannelForm: { padding: "8px 16px", display: "flex", flexDirection: "column", gap: "6px" },
  newChannelInput: { background: "var(--col-bg-input)", border: "1px solid var(--col-border)", borderRadius: "6px", padding: "6px 10px", color: "var(--col-text-primary)", fontSize: "13px", outline: "none" },
  newChannelRow: { display: "flex", gap: "6px" },
  newChannelSubmit: { padding: "6px 12px", background: "var(--col-accent)", borderRadius: "6px", color: "#fff", fontSize: "13px", fontWeight: 600, border: "none", cursor: "pointer" },
  privateToggle: { display: "flex", alignItems: "center", gap: "6px", fontSize: "12px", color: "var(--col-text-secondary)", cursor: "pointer" },
};
